routes/web.php
<?php

use App\Http\Controllers\Admin\Configuracoes\ConfiguracoesController;
use App\Http\Controllers\Admin\Encomenda\ListaDespesaController;
use App\Http\Controllers\Admin\EncomendaRecebidaLancha\EncomendaRecebidaLanchaController;
use App\Http\Controllers\Admin\LanchaController;
use App\Http\Controllers\Admin\Relatorio\PorDestino\GeralController;
use App\Http\Controllers\Admin\Relatorio\PorDestino\IndividualController;
use App\Http\Controllers\Admin\Relatorio\TodosDestinosDataLancha\TodosDestinosDataLanchaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\HomeController@index')->name('sistema.welcome');

Auth::routes();

Route::middleware('auth')->group(function() {
  Route::get('/home', 'Admin\HomeController@inicial')->name('sistema.home');
  Route::get('/sair', 'Admin\HomeController@logout')->name('sistema.sair');

  Route::prefix('encomendas_recebidas_lancha')->name('encomendas_recebidas_lancha.')->group(function() {
    Route::prefix('relatorio')->group(function() {
      Route::get('gerar-relatorio', [EncomendaRecebidaLanchaController::class, 'relatorioEncomendasGerarRelatorio'])->name('relatorio.gerar_relatorio');
      Route::get('alterar-status', [EncomendaRecebidaLanchaController::class, 'relatorioEncomendasAlterarStatus'])->name('relatorio.alterar_status');
      Route::get('lista', [EncomendaRecebidaLanchaController::class, 'relatorioEncomendasLista'])->name('relatorio.lista');
      Route::get('', [EncomendaRecebidaLanchaController::class, 'relatorioLanchaData'])->name('relatorio');
    });
    
    Route::get('imprimir-recibo/{id}', [EncomendaRecebidaLanchaController::class, 'imprimirRecibo'])->name('recibo');
  });

  Route::resource('encomendas_recebidas_lancha', 'Admin\EncomendaRecebidaLancha\EncomendaRecebidaLanchaController');
  Route::resource('lista_despesa', 'Admin\Relatorio\ListaDespesa\ListaDespesaController');
  
  Route::prefix('relatorio')->name('relatorio.')->group(function() {
    Route::get('por_lancha/gerar/{id}', 'Admin\Relatorio\PorLanchaController@gerarRelatorio')->name('por_lancha.gerar');
    Route::resource('por_lancha', 'Admin\Relatorio\PorLanchaController');
    
    Route::prefix('por_destino')->name('por_destino.')->group(function () {
      Route::get('individual/gerar/{id}', [IndividualController::class, 'gerarRelatorio'])->name('individual.gerar');
      Route::get('individual/lista_de_encomendas', [IndividualController::class, 'getListaDeEncomendas'])->name('individual.lista_de_encomendas');
      Route::resource('individual', 'Admin\Relatorio\PorDestino\IndividualController');
      
      Route::get('geral/gerar/{id}', [GeralController::class, 'gerarRelatorio'])->name('geral.gerar');
      Route::get('geral/lista_de_encomendas', [GeralController::class, 'getListaDeEncomendas'])->name('geral.lista_de_encomendas');
      Route::resource('geral', 'Admin\Relatorio\PorDestino\GeralController');
    });

    Route::prefix('todos-destinos-por-data-lancha')->group(function () {
      Route::get('gerar-relatorio/{data}/{lancha}', [TodosDestinosDataLanchaController::class, 'geraRelatorio']);
      // Route::get('gerar-relatorio/{data}/{lancha}', [TodosDestinosDataLanchaController::class, 'gerarPdf']);
    });
  });

  Route::get('lista-de-lanchas', [LanchaController::class, 'ListaDeLanchas']);
});


Route::prefix('configuracoes')->middleware(['configs'])->group(function ()
{
  Route::get('usuarios', [ConfiguracoesController::class, 'usuarios'])->name('sistema.configuracoes.usuarios');
  Route::get('usuarios/novo', [ConfiguracoesController::class, 'novoUsuario'])->name('sistema.configuracoes.novo_usuario');
  Route::get('usuarios/editar', [ConfiguracoesController::class, 'editarUsuario'])->name('sistema.configuracoes.editar_usuario');

  Route::get('lanchas', [ConfiguracoesController::class, 'lanchas'])->name('sistema.configuracoes.lanchas');
  Route::get('lanchas/{id_lancha}/alterar-status', [ConfiguracoesController::class, 'alterarStatusLancha'])->name('sistema.configuracoes.lancha.alterar_status');

  Route::get('municipios', [ConfiguracoesController::class, 'municipios'])->name('sistema.configuracoes.municipios');
  Route::get('municipios/{id_municipio}/alterar-status', [ConfiguracoesController::class, 'alterarStatusMunicipio'])->name('sistema.configuracoes.municipio.alterar_status');
});


Route::get('/encomenda/cadastro',                            'Admin\EncomendaController@create')->name('sistema.encomenda.cadastro');
Route::any('/encomenda/cadastro/pesquisar',                  'Admin\EncomendaController@pesquisarCadastro')->name('encomenda.cadastro');
Route::get('/encomenda/cadastro/auto',                       'Admin\EncomendaController@autocomplete')->name('autocomplete');
Route::post('/encomenda/lista',                              'Admin\EncomendaController@store')->name('encomenda.store');
Route::get('/encomenda/lista',                               'Admin\EncomendaController@index')->name('sistema.encomenda.lista');
Route::any('/encomenda/lista/pesquisar',                     'Admin\EncomendaController@pesquisarListaEncomenda')->name('encomenda.pesquisar');
Route::get('/encomenda/vizualizar/{id}',                     'Admin\EncomendaController@show')->name('sistema.encomenda.vizualizar');
Route::get('/encomenda/vizualizar/{id}/editar',              'Admin\EncomendaController@edit')->name('sistema.encomenda.editar');
Route::put('/encomenda/vizualizar/{id}',                     'Admin\EncomendaController@update')->name('sistema.encomenda.update');
Route::get('/encomenda/deletar/{id}',                        'Admin\EncomendaController@destroy')->name('sistema.encomenda.deletar');
Route::get('/encomenda/vizualizar-relatorio-individual',     'Admin\EncomendaController@relatorio')->name('sistema.encomenda.relatorio');
Route::post('/encomenda/vizualizar-relatorio-individual',    'Admin\EncomendaController@relatorioView')->name('encomenda.relatorioview');

Route::prefix('encomenda')->group(function () {
    Route::prefix('lista-despesas')->group(function () {
        Route::post('', [ListaDespesaController::class, 'store'])->name('encomenda.lista_despesas.store');
        Route::put('atualizar/{id}', [ListaDespesaController::class, 'update'])->name('encomenda.lista_despesas.update');
        Route::delete('deletar/{id}', [ListaDespesaController::class, 'destroy'])->name('encomenda.lista_despesas.destroy');
    });
});

Route::any('/encomendas-deletadas/lista/pesquisar',                     'Admin\EncomendaDeletadaController@pesquisarListaEncomenda')->name('encomenda_deletada.pesquisar');
Route::get('/encomendas-deletadas/deletar',                             'Admin\EncomendaDeletadaController@index')->name('sistema.encomendas_deletadas.index');
Route::get('/encomenda-deletadas/visualizar/{id}',                      'Admin\EncomendaDeletadaController@show')->name('sistema.encomendas_deletadas.visualizar');
Route::get('/encomenda-deletadas/retornar_encomenda/{id}',              'Admin\EncomendaDeletadaController@retornarEncomenda')->name('sistema.encomendas_deletadas.retornar_encomenda');
Route::get('/encomendas-deletadas/imprimir-recibo/{id}',                'Admin\EncomendaDeletadaController@imprimirRecibo')->name('sistema.encomendas_deletadas.recibo');
Route::get('/encomendas-deletadas/imprimir-cupom/{id}',                 'Admin\EncomendaDeletadaController@imprimirCupom')->name('sistema.encomendas_deletadas.cupom');

Route::get('/relatorio/valores-recebidos',                          'Admin\RelatorioController@relatorioValorRecebido')->name('sistema.relatorio.valores_recebidos_index');
Route::post('/relatorio/valores-recebidos',                         'Admin\RelatorioController@buscarRelatorioValorRecebido')->name('sistema.relatorio.valores_recebidos');

Route::get('/relatorio/destinos',                                   'Admin\RelatorioController@relatorioDestino')->name('sistema.relatorio.relatorio_destino');
Route::post('/relatorio/destinos',                                  'Admin\RelatorioController@relatorioDestinoView')->name('relatorio.relatorio_destino_view');
Route::get('/relatorio/destinos-todos',                             'Admin\RelatorioController@relatorioDestinoTodos')->name('sistema.relatorio.relatorio_destino_todos');
Route::post('/relatorio/destinos-todos',                            'Admin\RelatorioController@relatorioDestinoTodosView')->name('relatorio.relatorio_destino_todos_view');
Route::get('/relatorio',                                            'Admin\RelatorioController@index')->name('sistema.relatorio.index');
Route::get('/relatorio/historico',                                  'Admin\RelatorioController@historico')->name('sistema.relatorio.historico');
Route::get('/relatorio/vizualizar/{id}',                            'Admin\RelatorioController@show')->name('sistema.relatorio.vizualizar');
Route::get('/relatorio-todas-as-lanchas',                           'Admin\RelatorioController@relatorio')->name('sistema.relatorio.relatorio');
Route::post('/relatorio-todas-as-lanchas',                          'Admin\RelatorioController@relatorioView')->name('relatorio.todas_lancha');


Route::get('/encomenda/vizualizar-relatorio-individual/download-pdf', 'Admin\PdfController@relatorioIndividual')->name('pdf.relatorio_individual');
Route::get('/encomenda/vizualizar-relatorio-todas-as-lanchas/download-pdf', 'Admin\PdfController@todasAsLanchas')->name('pdf.todas_as_lanchas');
Route::get('/relatorios/destinos/imprimir-pdf', 'Admin\PdfController@imprimirDestinosPdf')->name('pdf.imprimir_destino_pdf');

resources/views/sistema/layout/head.blade.php
<head>
  <!-- Meta tags Obrigatórias -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="sortcut icon" href="{{asset('img/ajato_mini.png')}}" type="image/x-icon" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">


  <script src="https://kit.fontawesome.com/37f525ac36.js" crossorigin="anonymous"></script>

  <title>@yield('titulo')</title>

  @stack('estilos-local')
</head>

resources/views/sistema/layout/header.blade.php
<div class="p-0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" style="margin: 0px; width: 60px;" href="{{route('sistema.home')}}">
      <img src="{{asset('img/ajato_mini.png')}}" class="rounded img-fluid" alt="Ajato Encomendas">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Alterna navegação">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{route('encomendas_recebidas_lancha.index')}}"><i class="fas fa-crown"></i> Versão 2.0</a>
        </li>
        {{-- <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.home')}}"><i class="fas fa-home"></i> Home</a>
        </li> --}}
        <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.encomenda.cadastro')}}"><i class="fas fa-plus-circle"></i> Cadastro</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.encomenda.lista')}}"><i class="fas fa-clipboard-list"></i> Lista</a>
        </li>
        {{-- <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.lancha.index')}}"><i class="fas fa-ship"></i> Lancha</a>
        </li> --}}
        <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.relatorio.index')}}"><i class="fas fa-hand-holding-usd"></i> Relatório</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.relatorio.historico')}}"><i class="fas fa-history"></i> Historico de Relatórios Gerados</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('sistema.encomendas_deletadas.index')}}"><i class="fas fa-trash"></i> Deletados</a>
        </li>
      </ul>

      @if ($user->is_admin == 'S')
        <div class="btn-group mr-2">
          <button type="button" style="background-color:rgb(144, 179, 255);" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-gear"></i> Configurações
          </button>

          <div class="dropdown-menu">
            <a class="dropdown-item text-left" href="{{ route('sistema.configuracoes.usuarios') }}">
              <i class="fas fa-users"></i>
              Usuários
            </a>
            <a class="dropdown-item text-left" href="{{ route('sistema.configuracoes.lanchas') }}">
              <i class="fas fa-ship"></i>
              Lanchas
            </a>
            <a class="dropdown-item text-left" href="{{ route('sistema.configuracoes.municipios') }}">
              <i class="fas fa-map"></i> 
              Municipios
            </a>
          </div>
        </div>
      @endif

      <div class="btn-group mr-2">
        <button type="button" style="background-color:red;" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-exclamation-circle"></i> Resets 
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item text-left" href="{{route('sistema.reset.reset-encomenda')}}" onclick="return confirm('Deseja Resetar Encomendas?');"><i class="fas fa-exclamation-triangle"></i> Resetar Encomendas</a>
          <a class="dropdown-item text-left" href="{{route('sistema.reset.index')}}"><i class="fas fa-list-ol"></i> Listar Resets</a>
        </div>
      </div>

      <div class="btn-group">
        <button type="button" style="background-color:orange;" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ $user->name }} 
        </button>

        <div class="dropdown-menu">
          <a class="dropdown-item text-center" href="{{route('sistema.sair')}}">
            <i class="fas fa-sign-out-alt"></i> 
            Sair
          </a>
        </div>
      </div>
    </div>
  </nav>
</div>

resources/views/sistema/layout/index.blade.php
<!DOCTYPE html>
<html lang="pt-br">

  @include('sistema.layout.head')

  <body>

    @include('sistema.layout.header')

    <div class="p-3">
      @if (session('message') || session('error'))
        <div class="bg-dark text-white position-fixed p-3 mb-2 mr-2 w-50" style="z-index: 5; right: 0; bottom: 0; border-radius: 10px;">
          <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="false" data-delay="2000">
            <div class="toast-header">
              <strong class="mr-auto">Erros Encontrados!</strong>
            </div>

            <hr>
            
            <div class="toast-body">
              <ul>
                @if (session('message'))
                  @foreach (session('message') as $item)
                    <li>{{ $item }}</li>
                  @endforeach
                @else
                  @foreach (session('error') as $item)
                    <li>{{ $item }}</li>
                  @endforeach
                @endif
              </ul>
            </div>
          </div>
        </div>
      @endif

      @yield('conteudo')
    </div>

    @include('sistema.layout.java')

    @include('sistema.layout.footer')

    @stack('js')

  </body>
</html>

resources/views/sistema/layout/java.blade.php
<!-- JavaScript (Opcional) -->
<!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>